### PR TITLE
Updating runtimes of python and nodeJS

### PR DESCRIPTION
**Pull request by himsharma01**

### CODE REVIEW

**Comment by rymancl** [comment]
Looking forward to this! We just attempted to upgrade all of our `cloudwatchlogs-with-dlq` Lambda functions from `nodejs16.x` to `nodejs18.x` and they all blew up.

image

**Review by npande — APPROVED** [review]
LGTM

**Comment by himsharma01** [comment]
> Looking forward to this! We just attempted to upgrade all of our `cloudwatchlogs-with-dlq` Lambda functions from `nodejs16.x` to `nodejs18.x` and they all blew up.
> 
> image

@rymancl We have the released the lambdas with latest runtime supported. Thank you for your patience.
Also make sure to checkout the our latest [AWS Observability v2.7.0 release](https://github.com/SumoLogic/sumologic-solution-templates/releases/tag/v2.7.0).

**Comment by scastria** [comment]
I still see the same error when switching to nodejs18.  Have the S3 buckets where this lambda code is located been updated with this change?

**Comment by scastria** [comment]
I just ran:

`aws s3 cp s3://appdevzipfiles-us-west-2/cloudwatchlogs-with-dlq.zip .`

to check the content and I don't see any of the changes in the code for this fix

**Comment by rymancl** [comment]
Confirmed S3 is not updated. Last updated in January.

> aws s3api head-object --bucket appdevzipfiles-us-west-2 --key cloudwatchlogs-with-dlq.zip

```
{
    "AcceptRanges": "bytes",
    "LastModified": "2023-01-13T12:14:42+00:00",
    "ContentLength": 732358,
    "ETag": "\"9ae46e697262edd35468a8635e05970f\"",
    "ContentType": "binary/octet-stream",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

**Comment by himsharma01** [comment]
@rymancl @scastria the s3 location of the file has been changed to cloudwatchLogsDLQ/v1.2.0/cloudwatchlogs-with-dlq.zip inside s3 bucket appdevzipfiles-us-west-2.

**Comment by rymancl** [comment]
> @rymancl @scastria the s3 location of the file has been changed to `cloudwatchLogsDLQ/v1.2.0/cloudwatchlogs-with-dlq.zip `inside s3 bucket `appdevzipfiles-us-west-2`.

Interesting, thanks for noting that.

But that file still shows as last updated almost 2 months ago.

> aws s3api head-object --bucket appdevzipfiles-us-west-2 --key cloudwatchLogsDLQ/v1.2.0/cloudwatchlogs-with-dlq.zip

```
{
    "AcceptRanges": "bytes",
    "LastModified": "2023-09-07T13:23:03+00:00",
    "ContentLength": 732472,
    "ETag": "\"5f07cbcb6a6345c64e1876608c5d94ff\"",
    "ContentType": "binary/octet-stream",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

**Comment by scastria** [comment]
I do see the change in that new location.  Testing now...

**Comment by scastria** [comment]
Everything looks great!  Thanks.

**Pull request merged**
