### PR TITLE
Sourabh aws observability

### PR DESCRIPTION
**Pull request by SumoSourabh**
Changes related to AWS O V2. Moving to new hierarchy version. Added support for retries.

### CODE REVIEW

**Comment by himanshu219** [comment]
LGTM am curious though why we are copying the folder, can't we appended the app version in the folder name.

**Comment by himanshu219** [comment]
Also why did we name the class SumoLogicAWSExplorer shouldn't it be jst SumoLogicExplorer assuming one can create any hierarchy for example I want to create a Tracing hierarchy.

**Comment by SumoSourabh** [comment]
The CF will call delete even If I just append the App version (as we are creating a new App, the ID gets changed and CF calls delete). So first we have to copy the folder and let CF to it task of delete

**Comment by SumoSourabh** [comment]
> LGTM am curious though why we are copying the folder, can't we append the app version in the folder name.

The CF will call delete even If I just append the App version (as we are creating a new App, the ID gets changed and CF calls delete). So first we have to copy the folder and let CF to it task of delete

**Comment by SumoSourabh** [comment]
> Also why did we name the class SumoLogicAWSExplorer shouldn't it be jst SumoLogicExplorer assuming one can create any hierarchy for example if I want to create a Tracing hierarchy I can use it right?.

If we change the Name, then update fails as the update will not find SumoLogicAWSExplorer custom resource. Thus have to keep the name as it is.

**Comment by SumoSourabh** [comment]
> > Also why did we name the class SumoLogicAWSExplorer shouldn't it be jst SumoLogicExplorer assuming one can create any hierarchy for example if I want to create a Tracing hierarchy I can use it right?.
> 
> If we change the Name, then update fails as the update will not find SumoLogicAWSExplorer custom resource for delete operation. Thus have to keep the name as it is.

Yes, you will be able to create hierarchies with the same resource as it is generic in nature

**Review by himanshu219 — APPROVED** [review]

**Pull request merged**
